module.exports = {
  UNAUTHORIZED_VK: 'UNAUTHORIZED_VK',
  INVALID_FUNDS: 'IF',
  UNAUTHORIZED_VOUCHER_OWNER: 'UNAUTHORIZED_V',
  UNAUTHORIZED_OWNER: 'Ownable: caller is not the owner',
  ALREADY_PROCESSED: 'ALREADY_PROCESSED',
};
