resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: source
    type: pull-request
    check_every: 1h
    webhook_token: ((webhook_token))
    source:
      repository: ((source_repository_name))
      access_token: ((github_access_token))
      states:
        - OPEN
        - MERGED
        - CLOSED

  - name: node-builder-image
    type: docker-image
    source:
      repository: ((node_builder_image_repository_url))

jobs:
  - name: handle-pr-event
    plan:
      - in_parallel:
        - get: source
          trigger: true
          version: every
        - get: node-builder-image
      - task: handle-pr-event
        image: node-builder-image
        file: source/pipelines/builder/handle-pr-event/task.yaml
        params:
          GPG_KEY: ((gpg_key))
          CI_DEPLOYMENT_TYPE: ((ci_deployment_type))
          CI_DEPLOYMENT_LABEL: ((ci_deployment_label))
