/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IBosonRouter, IBosonRouterInterface } from "../IBosonRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdVoucher",
        type: "uint256",
      },
    ],
    name: "cancelOrFault",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdVoucher",
        type: "uint256",
      },
    ],
    name: "complain",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_party",
        type: "address",
      },
    ],
    name: "incrementCorrelationId",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdVoucher",
        type: "uint256",
      },
    ],
    name: "redeem",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdVoucher",
        type: "uint256",
      },
    ],
    name: "refund",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdSupply",
        type: "uint256",
      },
    ],
    name: "requestCancelOrFaultVoucherSet",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "metadata",
        type: "uint256[]",
      },
    ],
    name: "requestCreateOrderETHETH",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_tokenDepositAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_tokensSent",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "v",
        type: "uint8",
      },
      {
        internalType: "bytes32",
        name: "r",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "s",
        type: "bytes32",
      },
      {
        internalType: "uint256[]",
        name: "metadata",
        type: "uint256[]",
      },
    ],
    name: "requestCreateOrderETHTKNWithPermit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_tokenPriceAddress",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "metadata",
        type: "uint256[]",
      },
    ],
    name: "requestCreateOrderTKNETH",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_tokenPriceAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "_tokenDepositAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_tokensSent",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "v",
        type: "uint8",
      },
      {
        internalType: "bytes32",
        name: "r",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "s",
        type: "bytes32",
      },
      {
        internalType: "uint256[]",
        name: "metadata",
        type: "uint256[]",
      },
    ],
    name: "requestCreateOrderTKNTKNWithPermit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdSupply",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_issuer",
        type: "address",
      },
    ],
    name: "requestVoucherETHETH",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdSupply",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_issuer",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_tokensDeposit",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "v",
        type: "uint8",
      },
      {
        internalType: "bytes32",
        name: "r",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "s",
        type: "bytes32",
      },
    ],
    name: "requestVoucherETHTKNWithPermit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdSupply",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_issuer",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_tokensPrice",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "v",
        type: "uint8",
      },
      {
        internalType: "bytes32",
        name: "r",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "s",
        type: "bytes32",
      },
    ],
    name: "requestVoucherTKNETHWithPermit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdSupply",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_issuer",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_tokensSent",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "v",
        type: "uint8",
      },
      {
        internalType: "bytes32",
        name: "r",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "s",
        type: "bytes32",
      },
    ],
    name: "requestVoucherTKNTKNSameWithPermit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdSupply",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_issuer",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_tokensSent",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "vPrice",
        type: "uint8",
      },
      {
        internalType: "bytes32",
        name: "rPrice",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "sPrice",
        type: "bytes32",
      },
      {
        internalType: "uint8",
        name: "vDeposit",
        type: "uint8",
      },
      {
        internalType: "bytes32",
        name: "rDeposit",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "sDeposit",
        type: "bytes32",
      },
    ],
    name: "requestVoucherTKNTKNWithPermit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IBosonRouter__factory {
  static readonly abi = _abi;
  static createInterface(): IBosonRouterInterface {
    return new utils.Interface(_abi) as IBosonRouterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBosonRouter {
    return new Contract(address, _abi, signerOrProvider) as IBosonRouter;
  }
}
