/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IFundLimitsOracle,
  IFundLimitsOracleInterface,
} from "../IFundLimitsOracle";

const _abi = [
  {
    inputs: [],
    name: "getETHLimit",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_tokenAddress",
        type: "address",
      },
    ],
    name: "getTokenLimit",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_newLimit",
        type: "uint256",
      },
    ],
    name: "setETHLimit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_tokenAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_newLimit",
        type: "uint256",
      },
    ],
    name: "setTokenLimit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IFundLimitsOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IFundLimitsOracleInterface {
    return new utils.Interface(_abi) as IFundLimitsOracleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFundLimitsOracle {
    return new Contract(address, _abi, signerOrProvider) as IFundLimitsOracle;
  }
}
