/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IVoucherKernel,
  IVoucherKernelInterface,
} from "../IVoucherKernel";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_issuer",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_tokenIdSupply",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_qty",
        type: "uint256",
      },
    ],
    name: "burnSupplyOnPause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdVoucher",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_msgSender",
        type: "address",
      },
    ],
    name: "cancelOrFault",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdSupply",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_issuer",
        type: "address",
      },
    ],
    name: "cancelOrFaultVoucherSet",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdVoucher",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_msgSender",
        type: "address",
      },
    ],
    name: "complain",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdSupply",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "_paymentMethod",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "_tokenPrice",
        type: "address",
      },
      {
        internalType: "address",
        name: "_tokenDeposits",
        type: "address",
      },
    ],
    name: "createPaymentMethod",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_seller",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_validFrom",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_validTo",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_price",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_depositSe",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_depositBu",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_quantity",
        type: "uint256",
      },
    ],
    name: "createTokenSupplyID",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdSupply",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_issuer",
        type: "address",
      },
      {
        internalType: "address",
        name: "_holder",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "_paymentMethod",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "_correlationId",
        type: "uint256",
      },
    ],
    name: "fillOrder",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdSupply",
        type: "uint256",
      },
    ],
    name: "getBuyerOrderCosts",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdVoucher",
        type: "uint256",
      },
    ],
    name: "getIdSupplyFromVoucher",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdSupply",
        type: "uint256",
      },
    ],
    name: "getOrderCosts",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdVoucher",
        type: "uint256",
      },
    ],
    name: "getPromiseIdFromVoucherId",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_idx",
        type: "uint256",
      },
    ],
    name: "getPromiseKey",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenSupplyId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    name: "getRemQtyForSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdSupply",
        type: "uint256",
      },
    ],
    name: "getSellerDeposit",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdSupply",
        type: "uint256",
      },
    ],
    name: "getSupplyHolder",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdSupply",
        type: "uint256",
      },
    ],
    name: "getVoucherDepositToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdVoucher",
        type: "uint256",
      },
    ],
    name: "getVoucherHolder",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdSupply",
        type: "uint256",
      },
    ],
    name: "getVoucherPaymentMethod",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdSupply",
        type: "uint256",
      },
    ],
    name: "getVoucherPriceToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdVoucher",
        type: "uint256",
      },
    ],
    name: "getVoucherStatus",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdVoucher",
        type: "uint256",
      },
    ],
    name: "isInValidityPeriod",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdVoucher",
        type: "uint256",
      },
    ],
    name: "isVoucherTransferable",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdVoucher",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_msgSender",
        type: "address",
      },
    ],
    name: "redeem",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdVoucher",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_msgSender",
        type: "address",
      },
    ],
    name: "refund",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_cancelFaultPeriod",
        type: "uint256",
      },
    ],
    name: "setCancelFaultPeriod",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_cashierAddress",
        type: "address",
      },
    ],
    name: "setCashierAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_complainPeriod",
        type: "uint256",
      },
    ],
    name: "setComplainPeriod",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdVoucher",
        type: "uint256",
      },
    ],
    name: "setDepositsReleased",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdVoucher",
        type: "uint256",
      },
    ],
    name: "setPaymentReleased",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdSupply",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_newSeller",
        type: "address",
      },
    ],
    name: "setSupplyHolderOnTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdVoucher",
        type: "uint256",
      },
    ],
    name: "triggerExpiration",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenIdVoucher",
        type: "uint256",
      },
    ],
    name: "triggerFinalizeVoucher",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IVoucherKernel__factory {
  static readonly abi = _abi;
  static createInterface(): IVoucherKernelInterface {
    return new utils.Interface(_abi) as IVoucherKernelInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVoucherKernel {
    return new Contract(address, _abi, signerOrProvider) as IVoucherKernel;
  }
}
