/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { UsingHelpers, UsingHelpersInterface } from "../UsingHelpers";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "c__0x5777ee5b",
        type: "bytes32",
      },
    ],
    name: "c_0x5777ee5b",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060918061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80638de8acde14602d575b600080fd5b605660048036036020811015604157600080fd5b81019080803590602001909291905050506058565b005b5056fea2646970667358221220bfb4c695a9f6447d7d6d633b21eb20d6ebbbecbb2a8afa635bb242a7c84de94c64736f6c63430007010033";

export class UsingHelpers__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<UsingHelpers> {
    return super.deploy(overrides || {}) as Promise<UsingHelpers>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): UsingHelpers {
    return super.attach(address) as UsingHelpers;
  }
  connect(signer: Signer): UsingHelpers__factory {
    return super.connect(signer) as UsingHelpers__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): UsingHelpersInterface {
    return new utils.Interface(_abi) as UsingHelpersInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UsingHelpers {
    return new Contract(address, _abi, signerOrProvider) as UsingHelpers;
  }
}
