name: Publish pre-release to npm
on:
  release:
    types: [prereleased]
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      PROTOCOL_DEPLOYER_PRIVATE_KEY: 123456789abcdef123456789abcdef123456789abcdef123456789abcdef1234
      CC_TOKEN_DEPLOYER_PRIVATE_KEY: 123456789abcdef123456789abcdef123456789abcdef123456789abcdef1234
    steps:
      - uses: actions/checkout@v2
      - name: Set env RELEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: "12.20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - run: npm --allow-same-version --no-git-tag-version version "${{ env.RELEASE_VERSION }}"
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          tag: beta
          check-version: false
